controller_frequency: 10.0
ChannelController:
  waypoint_reached_dist: 0.3
  waypoint_reached_angle: 7.0

  goal_reached_dist: 0.15
  goal_reached_angle: 0.17

  min_tv: 0.10
  max_tv: 1.0
  min_rv: 0.0
  max_rv: 2.3
  min_inplace_rv: 0.1

  stopped_tv: 0.05
  stopped_rv: 0.1

  max_accel_tv: 2.0
  max_accel_rv: 2.3


  visualize_voronoi: true

